//! Build script for the zenoh-flat C layer.
//!
//! prebindgen part: read the `#[prebindgen]` items collected by `zenoh-flat`
//! and run them through the `lang::Cbindgen` adapter to produce a Rust file of
//! `extern "C"` wrappers. cbindgen part: turn that Rust file into a C header.

use prebindgen::lang::snake_case;
use std::path::PathBuf;
use syn::parse_quote as pq;

fn main() {
    let bindings_file = generate_flat_bindings();
    generate_c_headers(&bindings_file);
    generate_configure_header();
}

/// Emit `include/zenoh_flat_configure.h` mirroring the enabled Cargo features as
/// C `#define`s, so consumers (examples/tests) can `#if defined(...)` on the same
/// feature gates the generated ABI was built with. `ZENOH_FLAT_UNSTABLE_API`
/// guards the `unstable`-only API arity (e.g. the trailing `reliability` arg of
/// `z_session_put`/`z_session_delete`/`z_session_declare_publisher`).
/// `zenoh_flat.h` auto-includes this header (via cbindgen.toml `after_includes`).
fn generate_configure_header() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let path = PathBuf::from(&crate_dir)
        .join("include")
        .join("zenoh_flat_configure.h");
    let mut body = String::from(
        "/* Generated by zenoh-flat-c build.rs — feature configuration. Do not edit. */\n\
         #ifndef ZENOH_FLAT_CONFIGURE_H\n#define ZENOH_FLAT_CONFIGURE_H\n\n",
    );
    if std::env::var("CARGO_FEATURE_UNSTABLE").is_ok() {
        body.push_str("#define ZENOH_FLAT_UNSTABLE_API 1\n");
    }
    if std::env::var("CARGO_FEATURE_SHARED_MEMORY").is_ok() {
        body.push_str("#define ZENOH_FLAT_SHARED_MEMORY 1\n");
    }
    body.push_str("\n#endif /* ZENOH_FLAT_CONFIGURE_H */\n");
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    if let Err(e) = std::fs::write(&path, body) {
        println!("cargo:warning=Failed to write zenoh_flat_configure.h: {e}");
    }
}

/// Generate the Rust FFI bindings file from `zenoh-flat`'s prebindgen output.
fn generate_flat_bindings() -> PathBuf {
    // Reader over the data emitted by zenoh-flat's `#[prebindgen]` macro.
    let source = prebindgen::Source::new(zenoh_flat::PREBINDGEN_OUT_DIR);

    // C / cbindgen adapter.
    //
    // We wrap the C-facing low-level APIs that already have clean ownership and
    // error semantics for a native caller:
    // - key expressions via the `ZKeyExpr` opaque handle
    // - configs via the `ZConfig` opaque handle
    // - logger initialization helpers
    //
    // We deliberately do NOT wrap the high-level `KeyExpr` struct or its
    // `keyexpr_*` functions. Those use `impl Into<KeyExpr>` generics (not
    // `extern "C"`-able) and a string-caching struct designed for managed
    // languages like Java/Kotlin, where every native-boundary crossing is
    // expensive: there the key expression is held string-side and the native
    // `ZKeyExpr` is materialized lazily. That layer belongs to the JNI adapter,
    // not the C one.
    // Name-mangling rules: every C-facing name (types, destructors, callback
    // structs, function symbols) is generated from the Rust type/function, so the
    // declarations below carry no per-item `.name(...)`. The zenoh `z_…_t` / `z_…`
    // convention lives here, in this consumer — `lang::Cbindgen` stays universal.
    let mut cbindgen = prebindgen::lang::Cbindgen::new()
        .source_module(pq!(zenoh_flat))
        // Single universal raw-memory freer for the `char*` data the layer hands
        // out (string returns + data-struct `String` fields). Opaque handles keep
        // their own typed `*_drop`.
        .free_memory_function("z_free")
        // Base: strip the `Z` opaque-handle prefix, then `snake_case`, with the
        // few irregulars fixed in this one place (`KeyExpr`→`keyexpr` etc.).
        .mangle_rust_type(|short| match short {
            "KeyExpr" | "ZKeyExpr" => "keyexpr".to_string(),
            "ZBytes" | "ZZBytes" => "zbytes".to_string(),
            "ZenohId" | "ZZenohId" => "zenoh_id".to_string(),
            "WhatAmI" => "whatami".to_string(),
            other => snake_case(other.strip_prefix('Z').unwrap_or(other)),
        })
        // The flat API is the sole C API of this crate, so its names carry the
        // plain `z_` prefix (the zenoh convention).
        .mangle_type_name(|base| format!("z_{base}_t"))
        .mangle_destructor(|base| format!("z_{base}_drop"))
        .mangle_take(|base| format!("z_{base}_take"))
        .mangle_callback(|bases| {
            if bases.is_empty() {
                "z_closure_drop_t".to_string()
            } else {
                format!("z_closure_{}_t", bases.join("_"))
            }
        })
        // Functions are already `z_*` except the loggers — prefix those
        // (`init_android_logs` → `z_init_android_logs`).
        .mangle_function(|n| {
            if n.starts_with("z_") {
                n.to_string()
            } else {
                format!("z_{n}")
            }
        });

    for ty in [
        pq!(KeyExpr),
        pq!(Config),
        pq!(Session),
        pq!(Publisher),
        pq!(Querier),
        pq!(LivelinessToken),
        // Returned by the callback-declaring APIs (subscriber/queryable/scout).
        pq!(Subscriber),
        pq!(Queryable),
        pq!(Scout),
    ] {
        cbindgen = cbindgen.opaque_ptr(ty);
    }

    // `ZError` (`zenoh::Error = Box<dyn Error + Send + Sync>`) is the `E` of every
    // fallible `z_*` `Result`. It is opaque (not a by-value struct), so it is
    // marshalled to C as a `char*` message via `z_error_message(&e)`; the error
    // out-param of each wrapper becomes `char **e`.
    cbindgen = cbindgen.opaque_error(pq!(Error), pq!(error_get_message));

    // `ZZBytes` (the refcounted `zenoh::bytes::ZBytes`) is passed **inline by
    // value** (no `Box`) via an opaque `#[repr(C, align(8))] z_zbytes_t` of
    // identical size/align — eliminating the per-`z_publisher_put` malloc/free on
    // the throughput hot path while preserving zero-copy refcount sharing. The
    // opaque struct + its `Gravestone` impl are injected into the generated file
    // below; cbindgen emits transmute converters + fail-closed size/align asserts.
    cbindgen = cbindgen.opaque_owned_struct(pq!(ZBytes), pq!(z_zbytes_t));

    // `ZSample` (delivered to subscriber callbacks) is inline by value too, with a
    // `Sample::empty()` gravestone. Its owned callback param is marked
    // `.takeable_param(0)` below: the C callback receives `z_sample_t*` and may
    // take it (collect) via `z_sample_take` or just read it; the trampoline drops
    // it after the call. Eliminates the per-message box/free on the sub path.
    cbindgen = cbindgen.opaque_owned_struct(pq!(Sample), pq!(z_sample_t));

    // The remaining owned callback-argument types — same inline-by-value +
    // `T::empty()` gravestone + takeable-callback treatment as `ZSample`.
    cbindgen = cbindgen.opaque_owned_struct(pq!(Reply), pq!(z_reply_t));
    cbindgen = cbindgen.opaque_owned_struct(pq!(Query), pq!(z_query_t));
    cbindgen = cbindgen.opaque_owned_struct(pq!(Hello), pq!(z_hello_t));

    // `ZReplyError` (a failed reply's `{ payload: ZBytes, encoding: Encoding }`)
    // owns external data — inline by value with a `ReplyError::default()`
    // gravestone. Reached from a `ZReply` via the `Option` getter `z_reply_err`;
    // its own accessors are plain borrows.
    cbindgen = cbindgen.opaque_owned_struct(pq!(ReplyError), pq!(z_reply_error_t));

    // `ZTimestamp` (`uhlc::Timestamp`) is a small `Copy` POD that owns no external
    // data — inline it by value as `opaque_data_struct`. There is no per-message box to
    // eliminate here (the change just drops the boxed-handle indirection for the
    // borrowed-timestamp accessors); because it holds nothing, it needs **no
    // `Gravestone` impl** — only the autogenerated `Transmute`.
    cbindgen = cbindgen.opaque_data_struct(pq!(Timestamp), pq!(z_timestamp_t));

    // `ZZenohId` (`zenoh_config::wrappers::ZenohId` = a 16-byte `Copy` id) owns no
    // external data — inline it by value as `opaque_data_struct` (no `Gravestone`
    // needed). This removes the per-id `Box` on `z_session_zid` / `z_hello_zid` /
    // `z_reply_replier_zid`, and turns the `Vec<ZZenohId>` results of
    // `z_session_peers_zid` / `z_session_routers_zid` from an array of `N` boxed
    // pointers (N+1 allocations) into a single inline-struct array.
    cbindgen = cbindgen.opaque_data_struct(pq!(ZenohId), pq!(z_zenoh_id_t));

    // `ZEncoding` (`zenoh::bytes::Encoding` = `{ id, schema: Option<ZSlice> }`) owns
    // external data (the refcounted `schema`), so inline it by value as
    // `opaque_owned_struct` with an `Encoding::default()` gravestone. The borrow
    // accessors/inputs (`Option<&ZEncoding>`, the `&'static` constructors) are
    // unchanged; this drops the `Box` on the owned-returning `z_encoding_clone` /
    // `z_encoding_from_string` / `z_reply_error_encoding`.
    cbindgen = cbindgen.opaque_owned_struct(pq!(Encoding), pq!(z_encoding_t));

    // Whether the `unstable` feature is enabled for this build. Items gated by
    // `#[prebindgen(cfg = "feature = \"unstable\"")]` in zenoh-flat are only
    // present in the captured source when this is set, so their declarations
    // here must be guarded to match (declaring an absent item is an error).
    let unstable = std::env::var("CARGO_FEATURE_UNSTABLE").is_ok();

    for ty in [
        pq!(WhatAmI),
        pq!(CongestionControl),
        pq!(Priority),
        pq!(ConsolidationMode),
        pq!(QueryTarget),
        pq!(ReplyKeyExpr),
        pq!(SampleKind),
    ] {
        cbindgen = cbindgen.enum_type(ty);
    }
    if unstable {
        // `SetIntersectionLevel` (keyexpr relation) and `Reliability` mirror
        // `#[unstable]` zenoh APIs.
        cbindgen = cbindgen.enum_type(pq!(SetIntersectionLevel));
        cbindgen = cbindgen.enum_type(pq!(Reliability));
    }

    // Callback signatures of the `z_*` opaque-handle tier
    cbindgen = cbindgen
        .callback(pq!(impl Fn(Sample) + Send + Sync + 'static))
        .takeable_param(0)
        .callback(pq!(impl Fn(&Sample) + Send + Sync + 'static))
        .callback(pq!(impl Fn(Reply) + Send + Sync + 'static))
        .takeable_param(0)
        .callback(pq!(impl Fn(&Reply) + Send + Sync + 'static))
        .callback(pq!(impl Fn(Query) + Send + Sync + 'static))
        .takeable_param(0)
        .callback(pq!(impl Fn(&Query) + Send + Sync + 'static))
        .callback(pq!(impl Fn(Hello) + Send + Sync + 'static))
        .takeable_param(0)
        .callback(pq!(impl Fn(&Hello) + Send + Sync + 'static))
        .callback(pq!(impl Fn() + Send + Sync + 'static));

    // The C layer wraps the `z_*` opaque-handle tier, now including its callback
    // APIs (closure structs). The generic/value-layer `impl Into(...)` wrappers
    // (and value-struct returns) remain out of scope — they belong to the JNI
    // adapter.
    for (function, base_name) in [
        (pq!(keyexpr_new_try_from), Some("keyexpr_try_from")),
        (pq!(keyexpr_new_autocanonize), Some("keyexpr_autocanonize")),
        (pq!(keyexpr_new_join), Some("keyexpr_join")),
        (pq!(keyexpr_new_concat), Some("keyexpr_concat")),
        (pq!(config_new_default), Some("config_default")),
        (pq!(config_new_from_file), Some("config_from_file")),
        (pq!(config_new_from_json), Some("config_from_json")),
        (pq!(config_new_from_json5), Some("config_from_json5")),
        (pq!(config_new_from_yaml), Some("config_from_yaml")),
        (pq!(config_get_json), None),
        (pq!(config_insert_json5), None),
        (pq!(open), None),
        (pq!(session_declare_keyexpr), None),
        (pq!(session_undeclare_keyexpr), None),
        (pq!(session_close), None),
        // Explicit, callback-free operations taking concrete handles
        // (`&z_keyexpr_t`, `z_zbytes_t`, `&z_encoding_t`) — no `impl Into<…>`.
        // All return `Result<(), Error>`, so fallible inputs (including the
        // `Option<…>` attachments) route through the error out-param — no
        // `.panic()`. Only the callback APIs and the value-struct/`Vec<ZenohId>`
        // returns remain undeclared.
        (pq!(zbytes_new_from_slice), Some("zbytes_from_slice")),
        (pq!(session_declare_publisher), None),
        (pq!(session_declare_querier), None),
        (pq!(query_reply_error), None),
        // Callback APIs of the `z_*` tier (deliver borrowed opaque handles to a C
        // closure struct + zero-arg on-close). All return `Result<_, Error>`, so
        // fallible borrow/`Option` inputs route through the error out-param — no
        // `.panic()`.
        (pq!(session_declare_subscriber), None),
        (pq!(session_declare_queryable), None),
        (pq!(session_get), None),
        (pq!(scout), None),
        (pq!(liveliness_get), None),
        (pq!(liveliness_declare_subscriber), None),
        (pq!(querier_get), None),
        // Put/delete/reply ops, unblocked by `Option<T>` input support.
        (pq!(publisher_put), None),
        (pq!(publisher_delete), None),
        (pq!(publisher_undeclare), None),
        (pq!(session_put), None),
        (pq!(session_delete), None),
        (pq!(query_reply_success), None),
        (pq!(query_reply_delete), None),
        (pq!(querier_undeclare), None),
        (pq!(queryable_undeclare), None),
        (pq!(subscriber_undeclare), None),
        // Reply with a fully-formed owned `ZSample` (preserves kind + metadata);
        // returns `Result<(), Error>`, so its fallible inputs route through the
        // error out-param — no `.panic()`.
        (pq!(query_reply_sample), None),
        (pq!(liveliness_declare_token), None),
        (pq!(liveliness_undeclare_token), None),
        (
            pq!(encoding_const_zenoh_bytes),
            Some("encoding_zenoh_bytes"),
        ),
        (
            pq!(encoding_const_zenoh_string),
            Some("encoding_zenoh_string"),
        ),
        (
            pq!(encoding_const_zenoh_serialized),
            Some("encoding_zenoh_serialized"),
        ),
        (
            pq!(encoding_const_application_octet_stream),
            Some("encoding_application_octet_stream"),
        ),
        (pq!(encoding_const_text_plain), Some("encoding_text_plain")),
        (
            pq!(encoding_const_application_json),
            Some("encoding_application_json"),
        ),
        (pq!(encoding_const_text_json), Some("encoding_text_json")),
        (
            pq!(encoding_const_application_cdr),
            Some("encoding_application_cdr"),
        ),
        (
            pq!(encoding_const_application_cbor),
            Some("encoding_application_cbor"),
        ),
        (
            pq!(encoding_const_application_yaml),
            Some("encoding_application_yaml"),
        ),
        (pq!(encoding_const_text_yaml), Some("encoding_text_yaml")),
        (pq!(encoding_const_text_json5), Some("encoding_text_json5")),
        (
            pq!(encoding_const_application_python_serialized_object),
            Some("encoding_application_python_serialized_object"),
        ),
        (
            pq!(encoding_const_application_protobuf),
            Some("encoding_application_protobuf"),
        ),
        (
            pq!(encoding_const_application_java_serialized_object),
            Some("encoding_application_java_serialized_object"),
        ),
        (
            pq!(encoding_const_application_openmetrics_text),
            Some("encoding_application_openmetrics_text"),
        ),
        (pq!(encoding_const_image_png), Some("encoding_image_png")),
        (pq!(encoding_const_image_jpeg), Some("encoding_image_jpeg")),
        (pq!(encoding_const_image_gif), Some("encoding_image_gif")),
        (pq!(encoding_const_image_bmp), Some("encoding_image_bmp")),
        (pq!(encoding_const_image_webp), Some("encoding_image_webp")),
        (
            pq!(encoding_const_application_xml),
            Some("encoding_application_xml"),
        ),
        (
            pq!(encoding_const_application_x_www_form_urlencoded),
            Some("encoding_application_x_www_form_urlencoded"),
        ),
        (pq!(encoding_const_text_html), Some("encoding_text_html")),
        (pq!(encoding_const_text_xml), Some("encoding_text_xml")),
        (pq!(encoding_const_text_css), Some("encoding_text_css")),
        (
            pq!(encoding_const_text_javascript),
            Some("encoding_text_javascript"),
        ),
        (
            pq!(encoding_const_text_markdown),
            Some("encoding_text_markdown"),
        ),
        (pq!(encoding_const_text_csv), Some("encoding_text_csv")),
        (
            pq!(encoding_const_application_sql),
            Some("encoding_application_sql"),
        ),
        (
            pq!(encoding_const_application_coap_payload),
            Some("encoding_application_coap_payload"),
        ),
        (
            pq!(encoding_const_application_json_patch_json),
            Some("encoding_application_json_patch_json"),
        ),
        (
            pq!(encoding_const_application_json_seq),
            Some("encoding_application_json_seq"),
        ),
        (
            pq!(encoding_const_application_jsonpath),
            Some("encoding_application_jsonpath"),
        ),
        (
            pq!(encoding_const_application_jwt),
            Some("encoding_application_jwt"),
        ),
        (
            pq!(encoding_const_application_mp4),
            Some("encoding_application_mp4"),
        ),
        (
            pq!(encoding_const_application_soap_xml),
            Some("encoding_application_soap_xml"),
        ),
        (
            pq!(encoding_const_application_yang),
            Some("encoding_application_yang"),
        ),
        (pq!(encoding_const_audio_aac), Some("encoding_audio_aac")),
        (pq!(encoding_const_audio_flac), Some("encoding_audio_flac")),
        (pq!(encoding_const_audio_mp4), Some("encoding_audio_mp4")),
        (pq!(encoding_const_audio_ogg), Some("encoding_audio_ogg")),
        (
            pq!(encoding_const_audio_vorbis),
            Some("encoding_audio_vorbis"),
        ),
        (pq!(encoding_const_video_h261), Some("encoding_video_h261")),
        (pq!(encoding_const_video_h263), Some("encoding_video_h263")),
        (pq!(encoding_const_video_h264), Some("encoding_video_h264")),
        (pq!(encoding_const_video_h265), Some("encoding_video_h265")),
        (pq!(encoding_const_video_h266), Some("encoding_video_h266")),
        (pq!(encoding_const_video_mp4), Some("encoding_video_mp4")),
        (pq!(encoding_const_video_ogg), Some("encoding_video_ogg")),
        (pq!(encoding_const_video_raw), Some("encoding_video_raw")),
        (pq!(encoding_const_video_vp8), Some("encoding_video_vp8")),
        (pq!(encoding_const_video_vp9), Some("encoding_video_vp9")),
    ] {
        cbindgen = cbindgen.function(function);
        if let Some(base_name) = base_name {
            cbindgen = cbindgen.base_name(base_name);
        }
    }

    // Predicates over borrowed handles returning `bool`. They have fallible
    // (null-checked) borrow inputs but no `Result` channel, so `.panic()`
    // lets the wrapper abort on a null handle.
    cbindgen = cbindgen.function(pq!(keyexpr_intersects)).panic();
    cbindgen = cbindgen.function(pq!(keyexpr_includes)).panic();

    // Borrowed-handle relation returning the `SetIntersectionLevel` enum —
    // also `.panic()` (fallible borrows, no `Result`). Unstable-gated.
    if unstable {
        cbindgen = cbindgen.function(pq!(keyexpr_relation_to)).panic();
        cbindgen = cbindgen
            .function(pq!(reply_get_replier_zid))
            .base_name("reply_replier_zid")
            .panic(); // Option<ZenohId>
        cbindgen = cbindgen
            .function(pq!(reply_get_replier_eid))
            .base_name("reply_replier_eid")
            .panic();
        // Unstable sample metadata getters (`&ZSample` borrow, no `Result`).
        cbindgen = cbindgen
            .function(pq!(sample_get_reliability))
            .base_name("sample_reliability")
            .panic(); // Reliability enum
        cbindgen = cbindgen
            .function(pq!(sample_get_source_zid))
            .base_name("sample_source_zid")
            .panic(); // Option<ZenohId>
        cbindgen = cbindgen
            .function(pq!(sample_get_source_eid))
            .base_name("sample_source_eid")
            .panic(); // i32
        cbindgen = cbindgen
            .function(pq!(sample_get_source_sn))
            .base_name("sample_source_sn")
            .panic(); // i64
    }

    for (function, base_name) in [
        (pq!(keyexpr_new_clone), Some("keyexpr_clone")),
        (pq!(config_new_clone), Some("config_clone")),
        (pq!(zenoh_id_to_string), None),
        (pq!(hello_get_whatami), Some("hello_whatami")),
        (pq!(hello_get_zid), Some("hello_zid")),
        (pq!(encoding_get_id), Some("encoding_id")),
        (pq!(encoding_to_string), None),
        (pq!(encoding_new_from_string), Some("encoding_from_string")),
        (pq!(encoding_new_from_id), Some("encoding_from_id")),
        (pq!(encoding_new_with_schema), Some("encoding_with_schema")),
        (pq!(timestamp_get_ntp64), Some("timestamp_ntp64")),
        (pq!(session_is_closed), None),
        (pq!(session_new_timestamp), Some("session_new_timestamp")),
        (pq!(publisher_get_keyexpr), Some("publisher_keyexpr")),
        (pq!(querier_get_keyexpr), Some("querier_keyexpr")),
        (pq!(subscriber_get_keyexpr), Some("subscriber_keyexpr")),
        (pq!(queryable_get_keyexpr), Some("queryable_keyexpr")),
        (pq!(reply_is_ok), None),
        (pq!(reply_error_get_payload), Some("reply_error_payload")), // &ReplyError → &ZBytes borrow
        (pq!(reply_error_get_encoding), Some("reply_error_encoding")), // &ReplyError → &Encoding borrow
        (pq!(sample_get_key_expr), Some("sample_key_expr")),
        (pq!(sample_get_payload), Some("sample_payload")),
        (pq!(sample_get_encoding), Some("sample_encoding")),
        (pq!(sample_get_kind), Some("sample_kind")),
        (pq!(sample_get_express), Some("sample_express")),
        (pq!(sample_get_priority), Some("sample_priority")),
        (
            pq!(sample_get_congestion_control),
            Some("sample_congestion_control"),
        ),
        (pq!(query_get_keyexpr), Some("query_keyexpr")), // &KeyExpr borrow
        (pq!(query_get_parameters), Some("query_parameters")), // owned String → char*
        (pq!(keyexpr_to_string), None),                  // owned String → char*
        (pq!(encoding_new_clone), Some("encoding_clone")), // owned Encoding handle
        (pq!(zbytes_new_clone), Some("zbytes_clone")), // owned ZBytes handle (cheap refcount clone)
        // Sample constructors: build an owned `ZSample` (Put / Delete) from a
        // key-expr/payload + optional metadata. No `Result` channel, so their
        // fallible (owned/borrow) inputs use `.panic()`, like z_encoding_clone.
        (pq!(sample_new_put), Some("sample_put")),
        (pq!(sample_new_delete), Some("sample_delete")),
    ] {
        cbindgen = cbindgen.function(function).panic();
        if let Some(base_name) = base_name {
            cbindgen = cbindgen.base_name(base_name);
        }
    }

    // `Option<T>` getters: NULL encodes `None` on the wire, so NULL can no
    // longer double as an error channel — their null-checked borrow inputs
    // need `.panic()`. All inner `T` lower to a pointer wire (`String` →
    // `char*`, the rest to declared opaque handles).
    for (function, base_name) in [
        (pq!(encoding_get_schema), Some("encoding_schema")), // Option<String>
        (pq!(sample_get_timestamp), Some("sample_timestamp")), // Option<Timestamp>
        (pq!(sample_get_attachment), Some("sample_attachment")), // Option<ZBytes>
        (pq!(reply_get_sample), Some("reply_sample")),       // Option<Sample>
        (pq!(reply_get_err), Some("reply_err")),             // Option<ReplyError>
        (pq!(query_get_payload), Some("query_payload")),     // Option<&ZBytes> borrow
        (pq!(query_get_attachment), Some("query_attachment")), // Option<&ZBytes> borrow
        (pq!(query_get_encoding), Some("query_encoding")),   // Option<&Encoding> borrow
    ] {
        cbindgen = cbindgen.function(function).panic();
        if let Some(base_name) = base_name {
            cbindgen = cbindgen.base_name(base_name);
        }
    }

    // `Vec<T>` getters: lower to a malloc'd array (`T* + size_t`) freed C-side
    // via the `z_free_array` macro. Their null-checked `&handle` borrow inputs
    // have no `Result` channel, so `.panic()`. (`z_zbytes_from_slice`, a `&[u8]`
    // slice input, is infallible and declared in the plain `.function` loop.)
    for (function, base_name) in [
        (pq!(hello_get_locators), Some("hello_locators")), // Vec<String>
        (pq!(zenoh_id_to_bytes), None),                    // Vec<u8>
        (pq!(timestamp_get_id), Some("timestamp_id")),     // Vec<u8>
        (pq!(session_get_peers_zid), Some("session_peers_zid")), // Vec<ZenohId>
        (pq!(session_get_routers_zid), Some("session_routers_zid")), // Vec<ZenohId>
    ] {
        cbindgen = cbindgen.function(function).panic();
        if let Some(base_name) = base_name {
            cbindgen = cbindgen.base_name(base_name);
        }
    }
    // C still receives an owned byte array, but the Rust source accessor can use
    // `Cow<[u8]>` to avoid forcing an intermediate owned Vec for other adapters.
    cbindgen = cbindgen
        .function(pq!(zbytes_as_bytes))
        .base_name("zbytes_to_bytes")
        .panic();

    // Opaque-handle zid accessor: returns the `ZZenohId` handle (`&ZSession`
    // borrow is fallible, no `Result`, so `.panic()`).
    cbindgen = cbindgen
        .function(pq!(session_get_zid))
        .base_name("session_zid")
        .panic();

    // Logger helpers. The function mangler adds the `z_` prefix (these are the
    // only declared functions not already `z_*`).
    cbindgen = cbindgen
        .function(pq!(init_android_logs))
        .panic()
        .function(pq!(try_init_zenoh_logs_from_env))
        .function(pq!(init_zenoh_logs_from_env_or))
        .panic();

    let mut registry =
        prebindgen::core::Registry::from_items(source.items_all()).expect("scan prebindgen items");

    let bindings_file = registry
        .write_rust(&cbindgen, "zenoh_flat.rs")
        .expect("write generated bindings");

    // Inject the inline-by-value opaque counterpart `z_zbytes_t` (same size/align
    // as `ZZBytes`) at the top of the generated file, so it is compiled into the
    // cdylib AND seen by cbindgen (which parses this file). Its `Gravestone` impl
    // is hand-written in `src/gravestone.rs` (type-specific empty-state knowledge).
    //
    // The size/alignment are always obtained from a `prebindgen-opaque-types`
    // probe crate built for `$TARGET` (never from `size_of` in this build script).
    // The probe compiles a *normal* dependency on `zenoh-flat` with the cdylib's
    // exact `FEATURES`, so its layout matches the cdylib's regardless of (a)
    // cross-compilation and (b) Cargo feature unification differing between normal
    // deps and build-deps. The source crate locates itself via its
    // prebindgen-exported `MANIFEST_DIR`; the size/align asserts cbindgen emits
    // guard it fail-closed regardless.
    let opaque = prebindgen_opaque_types::OpaqueTypes::new(zenoh_flat::MANIFEST_DIR)
        .features(zenoh_flat::FEATURES)
        .add(pq!(zenoh_flat::ZBytes), pq!(z_zbytes_t))
        .add(pq!(zenoh_flat::Sample), pq!(z_sample_t))
        .add(pq!(zenoh_flat::Reply), pq!(z_reply_t))
        .add(pq!(zenoh_flat::ReplyError), pq!(z_reply_error_t))
        .add(pq!(zenoh_flat::Query), pq!(z_query_t))
        .add(pq!(zenoh_flat::Hello), pq!(z_hello_t))
        .add(pq!(zenoh_flat::Timestamp), pq!(z_timestamp_t))
        .add(pq!(zenoh_flat::ZenohId), pq!(z_zenoh_id_t))
        .add(pq!(zenoh_flat::Encoding), pq!(z_encoding_t))
        .generate()
        .expect("probe ZBytes size/alignment for z_zbytes_t");
    let body = std::fs::read_to_string(&bindings_file).expect("read generated bindings");
    std::fs::write(&bindings_file, format!("{opaque}\n{body}")).expect("inject opaque type");

    println!(
        "cargo:warning=Generated bindings at: {}",
        bindings_file.display()
    );

    bindings_file
}

/// Generate the C header from the prebindgen-generated Rust file via cbindgen.
fn generate_c_headers(bindings_file: &PathBuf) {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let config = cbindgen::Config::from_root_or_default(&crate_dir);

    let header_path = PathBuf::from(&out_dir).join("zenoh_flat.h");

    match cbindgen::Builder::new()
        .with_config(config)
        .with_src(bindings_file)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(&header_path);
            // The inline-by-value `z_zbytes_t` is emitted complete and aligned by
            // cbindgen directly, via `[layout] aligned_n = "ALIGN"` + the
            // per-platform `ALIGN(n)` macro in `cbindgen.toml`'s `after_includes`
            // (no header post-processing, and portable to MSVC).
            //
            // Also publish the header to the in-tree, deterministic `include/`
            // dir so C consumers (and the CMake build) have a stable path.
            // `zenoh_flat.h` is the crate's sole C API (plain `z_*` symbols).
            let stable = PathBuf::from(&crate_dir)
                .join("include")
                .join("zenoh_flat.h");
            if let Some(parent) = stable.parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            if let Err(e) = std::fs::copy(&header_path, &stable) {
                println!("cargo:warning=Failed to copy header to include/: {e}");
            }
            println!(
                "cargo:warning=Generated C headers at: {} (and {})",
                header_path.display(),
                stable.display()
            );
        }
        Err(e) => {
            println!("cargo:warning=Failed to generate C headers: {e:?}");
        }
    }
}
