/* Generated by cbindgen for zenoh-flat bindings */

#ifndef ZENOH_FLAT_H
#define ZENOH_FLAT_H

/* Generated with cbindgen:0.29.3 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#include "zenoh_flat_configure.h"

#if defined(_MSC_VER)
#define ALIGN(n) __declspec(align(n))
#else
#define ALIGN(n) __attribute__((aligned(n)))
#endif

#define z_free_array(array, len, elem_drop) \
    do { \
        if (array) { \
            for (size_t _z_i = 0; _z_i < (size_t)(len); _z_i++) { \
                elem_drop((array)[_z_i]); \
            } \
            z_free((void *)(array)); \
        } \
    } while (0)

typedef enum {
  Router = 1,
  Peer = 2,
  Client = 4,
} z_whatami_t;

typedef enum {
  Drop = 0,
  Block = 1,
} z_congestion_control_t;

typedef enum {
  Put = 0,
  Delete = 1,
} z_sample_kind_t;

typedef enum {
  RealTime = 1,
  InteractiveHigh = 2,
  InteractiveLow = 3,
  DataHigh = 4,
  Data = 5,
  DataLow = 6,
  Background = 7,
} z_priority_t;

typedef enum {
  BestMatching = 0,
  All = 1,
  AllComplete = 2,
} z_query_target_t;

typedef enum {
  Auto = 0,
  None = 1,
  Monotonic = 2,
  Latest = 3,
} z_consolidation_mode_t;

typedef enum {
  Any = 0,
  MatchingQuery = 1,
} z_reply_key_expr_t;

typedef struct {
  uint8_t _private[0];
} z_config_t;

typedef struct {
  char *message;
} z_error_t;

typedef struct ALIGN(8) {
  uint8_t _0[40];
} z_encoding_t;

typedef struct ALIGN(8) {
  uint8_t _0[48];
} z_hello_t;

typedef struct ALIGN(1) {
  uint8_t _0[16];
} z_zenoh_id_t;

typedef struct {
  uint8_t _private[0];
} z_keyexpr_t;

typedef struct {
  uint8_t _private[0];
} z_subscriber_t;

typedef struct {
  uint8_t _private[0];
} z_session_t;

typedef struct ALIGN(8) {
  uint8_t _0[184];
} z_sample_t;

typedef struct {
  void *context;
  void (*call)(z_sample_t*, void*);
  void (*drop)(void*);
} z_closure_sample_t;

typedef struct {
  void *context;
  void (*call)(void*);
  void (*drop)(void*);
} z_closure_drop_t;

typedef struct {
  uint8_t _private[0];
} z_liveliness_token_t;

typedef struct ALIGN(8) {
  uint8_t _0[184];
} z_reply_t;

typedef struct {
  void *context;
  void (*call)(z_reply_t*, void*);
  void (*drop)(void*);
} z_closure_reply_t;

typedef struct {
  uint8_t _private[0];
} z_publisher_t;

typedef struct ALIGN(8) {
  uint8_t _0[32];
} z_zbytes_t;

typedef struct {
  uint8_t _private[0];
} z_querier_t;

typedef struct ALIGN(8) {
  uint8_t _0[136];
} z_query_t;

typedef struct {
  uint8_t _private[0];
} z_queryable_t;

typedef struct ALIGN(8) {
  uint8_t _0[24];
} z_timestamp_t;

typedef struct {
  uint8_t _private[0];
} z_scout_t;

typedef struct {
  void *context;
  void (*call)(z_hello_t*, void*);
  void (*drop)(void*);
} z_closure_hello_t;

typedef struct {
  void *context;
  void (*call)(z_query_t*, void*);
  void (*drop)(void*);
} z_closure_query_t;

z_config_t *z_config_clone(const z_config_t *c);

z_config_t *z_config_default(void);

void z_config_drop(z_config_t *this_);

z_config_t *z_config_from_file(const char *path, z_error_t *e);

z_config_t *z_config_from_json(const char *s, z_error_t *e);

z_config_t *z_config_from_json5(const char *s, z_error_t *e);

z_config_t *z_config_from_yaml(const char *s, z_error_t *e);

char *z_config_get_json(const z_config_t *c, const char *key, z_error_t *e);

bool z_config_insert_json5(z_config_t *c, const char *key, const char *value, z_error_t *e);

const z_encoding_t *z_encoding_application_cbor(void);

const z_encoding_t *z_encoding_application_cdr(void);

const z_encoding_t *z_encoding_application_coap_payload(void);

const z_encoding_t *z_encoding_application_java_serialized_object(void);

const z_encoding_t *z_encoding_application_json(void);

const z_encoding_t *z_encoding_application_json_patch_json(void);

const z_encoding_t *z_encoding_application_json_seq(void);

const z_encoding_t *z_encoding_application_jsonpath(void);

const z_encoding_t *z_encoding_application_jwt(void);

const z_encoding_t *z_encoding_application_mp4(void);

const z_encoding_t *z_encoding_application_octet_stream(void);

const z_encoding_t *z_encoding_application_openmetrics_text(void);

const z_encoding_t *z_encoding_application_protobuf(void);

const z_encoding_t *z_encoding_application_python_serialized_object(void);

const z_encoding_t *z_encoding_application_soap_xml(void);

const z_encoding_t *z_encoding_application_sql(void);

const z_encoding_t *z_encoding_application_x_www_form_urlencoded(void);

const z_encoding_t *z_encoding_application_xml(void);

const z_encoding_t *z_encoding_application_yaml(void);

const z_encoding_t *z_encoding_application_yang(void);

const z_encoding_t *z_encoding_audio_aac(void);

const z_encoding_t *z_encoding_audio_flac(void);

const z_encoding_t *z_encoding_audio_mp4(void);

const z_encoding_t *z_encoding_audio_ogg(void);

const z_encoding_t *z_encoding_audio_vorbis(void);

z_encoding_t z_encoding_clone(const z_encoding_t *e);

void z_encoding_drop(z_encoding_t *this_);

z_encoding_t z_encoding_from_string(const char *s);

int32_t z_encoding_id(const z_encoding_t *e);

const z_encoding_t *z_encoding_image_bmp(void);

const z_encoding_t *z_encoding_image_gif(void);

const z_encoding_t *z_encoding_image_jpeg(void);

const z_encoding_t *z_encoding_image_png(void);

const z_encoding_t *z_encoding_image_webp(void);

char *z_encoding_schema(const z_encoding_t *e);

const z_encoding_t *z_encoding_text_css(void);

const z_encoding_t *z_encoding_text_csv(void);

const z_encoding_t *z_encoding_text_html(void);

const z_encoding_t *z_encoding_text_javascript(void);

const z_encoding_t *z_encoding_text_json(void);

const z_encoding_t *z_encoding_text_json5(void);

const z_encoding_t *z_encoding_text_markdown(void);

const z_encoding_t *z_encoding_text_plain(void);

const z_encoding_t *z_encoding_text_xml(void);

const z_encoding_t *z_encoding_text_yaml(void);

char *z_encoding_to_string(const z_encoding_t *e);

const z_encoding_t *z_encoding_video_h261(void);

const z_encoding_t *z_encoding_video_h263(void);

const z_encoding_t *z_encoding_video_h264(void);

const z_encoding_t *z_encoding_video_h265(void);

const z_encoding_t *z_encoding_video_h266(void);

const z_encoding_t *z_encoding_video_mp4(void);

const z_encoding_t *z_encoding_video_ogg(void);

const z_encoding_t *z_encoding_video_raw(void);

const z_encoding_t *z_encoding_video_vp8(void);

const z_encoding_t *z_encoding_video_vp9(void);

const z_encoding_t *z_encoding_zenoh_bytes(void);

const z_encoding_t *z_encoding_zenoh_serialized(void);

const z_encoding_t *z_encoding_zenoh_string(void);

void z_free(void *p);

void z_hello_drop(z_hello_t *this_);

char **z_hello_locators(const z_hello_t *h, uintptr_t *len);

void z_hello_take(z_hello_t *dst, z_hello_t *src);

z_whatami_t z_hello_whatami(const z_hello_t *h);

z_zenoh_id_t z_hello_zid(const z_hello_t *h);

void z_init_android_logs(const char *filter);

void z_init_zenoh_logs_from_env_or(const char *fallback_filter);

z_keyexpr_t *z_keyexpr_autocanonize(const char *s, z_error_t *e);

z_keyexpr_t *z_keyexpr_clone(const z_keyexpr_t *ke);

z_keyexpr_t *z_keyexpr_concat(const z_keyexpr_t *a, const char *b, z_error_t *e);

void z_keyexpr_drop(z_keyexpr_t *this_);

bool z_keyexpr_includes(const z_keyexpr_t *a, const z_keyexpr_t *b);

bool z_keyexpr_intersects(const z_keyexpr_t *a, const z_keyexpr_t *b);

z_keyexpr_t *z_keyexpr_join(const z_keyexpr_t *a, const char *b, z_error_t *e);

char *z_keyexpr_to_string(const z_keyexpr_t *ke);

z_keyexpr_t *z_keyexpr_try_from(const char *s, z_error_t *e);

z_subscriber_t *z_liveliness_declare_subscriber(const z_session_t *session,
                                                z_keyexpr_t *key_expr,
                                                bool history,
                                                z_closure_sample_t callback,
                                                z_closure_drop_t on_close,
                                                z_error_t *e);

z_liveliness_token_t *z_liveliness_declare_token(const z_session_t *session,
                                                 z_keyexpr_t *key_expr,
                                                 z_error_t *e);

bool z_liveliness_get(const z_session_t *session,
                      const z_keyexpr_t *key_expr,
                      int64_t timeout_ms,
                      z_closure_reply_t callback,
                      z_closure_drop_t on_close,
                      z_error_t *e);

void z_liveliness_token_drop(z_liveliness_token_t *this_);

z_session_t *z_open(z_config_t *config, z_error_t *e);

bool z_publisher_delete(const z_publisher_t *publisher, z_zbytes_t *attachment, z_error_t *e);

void z_publisher_drop(z_publisher_t *this_);

bool z_publisher_put(const z_publisher_t *publisher,
                     z_zbytes_t *payload,
                     const z_encoding_t *encoding,
                     z_zbytes_t *attachment,
                     z_error_t *e);

void z_querier_drop(z_querier_t *this_);

bool z_querier_get(const z_querier_t *querier,
                   const char *parameters,
                   z_zbytes_t *payload,
                   const z_encoding_t *encoding,
                   z_zbytes_t *attachment,
                   z_closure_reply_t callback,
                   z_closure_drop_t on_close,
                   z_error_t *e);

void z_query_drop(z_query_t *this_);

const z_encoding_t *z_query_encoding(const z_query_t *q);

const z_keyexpr_t *z_query_keyexpr(const z_query_t *q);

char *z_query_parameters(const z_query_t *q);

const z_zbytes_t *z_query_payload(const z_query_t *q);

bool z_query_reply_delete(const z_query_t *query,
                          const z_keyexpr_t *key_expr,
                          const int64_t *timestamp_ntp64,
                          z_zbytes_t *attachment,
                          const bool *express,
                          z_error_t *e);

bool z_query_reply_error(const z_query_t *query,
                         z_zbytes_t *payload,
                         const z_encoding_t *encoding,
                         z_error_t *e);

bool z_query_reply_success(const z_query_t *query,
                           const z_keyexpr_t *key_expr,
                           z_zbytes_t *payload,
                           const z_encoding_t *encoding,
                           const int64_t *timestamp_ntp64,
                           z_zbytes_t *attachment,
                           const bool *express,
                           z_error_t *e);

void z_query_take(z_query_t *dst, z_query_t *src);

void z_queryable_drop(z_queryable_t *this_);

void z_reply_drop(z_reply_t *this_);

const z_encoding_t *z_reply_error_encoding(const z_reply_t *r);

const z_zbytes_t *z_reply_error_payload(const z_reply_t *r);

bool z_reply_is_ok(const z_reply_t *r);

const z_sample_t *z_reply_sample(const z_reply_t *r);

void z_reply_take(z_reply_t *dst, z_reply_t *src);

const z_zbytes_t *z_sample_attachment(const z_sample_t *s);

z_congestion_control_t z_sample_congestion_control(const z_sample_t *s);

void z_sample_drop(z_sample_t *this_);

const z_encoding_t *z_sample_encoding(const z_sample_t *s);

bool z_sample_express(const z_sample_t *s);

const z_keyexpr_t *z_sample_key_expr(const z_sample_t *s);

z_sample_kind_t z_sample_kind(const z_sample_t *s);

const z_zbytes_t *z_sample_payload(const z_sample_t *s);

z_priority_t z_sample_priority(const z_sample_t *s);

void z_sample_take(z_sample_t *dst, z_sample_t *src);

const z_timestamp_t *z_sample_timestamp(const z_sample_t *s);

z_scout_t *z_scout(int32_t whatami,
                   const z_config_t *config,
                   z_closure_hello_t callback,
                   z_closure_drop_t on_close,
                   z_error_t *e);

void z_scout_drop(z_scout_t *this_);

z_keyexpr_t *z_session_declare_keyexpr(const z_session_t *session,
                                       const char *key_expr,
                                       z_error_t *e);

z_publisher_t *z_session_declare_publisher(const z_session_t *session,
                                           z_keyexpr_t *key_expr,
                                           const z_congestion_control_t *congestion_control,
                                           const z_priority_t *priority,
                                           const bool *express,
                                           z_error_t *e);

z_querier_t *z_session_declare_querier(const z_session_t *session,
                                       z_keyexpr_t *key_expr,
                                       const z_query_target_t *target,
                                       const z_consolidation_mode_t *consolidation,
                                       const z_congestion_control_t *congestion_control,
                                       const z_priority_t *priority,
                                       const bool *express,
                                       const int64_t *timeout_ms,
                                       const z_reply_key_expr_t *accept_replies,
                                       z_error_t *e);

z_queryable_t *z_session_declare_queryable(const z_session_t *session,
                                           z_keyexpr_t *key_expr,
                                           const bool *complete,
                                           z_closure_query_t callback,
                                           z_closure_drop_t on_close,
                                           z_error_t *e);

z_subscriber_t *z_session_declare_subscriber(const z_session_t *session,
                                             z_keyexpr_t *key_expr,
                                             z_closure_sample_t callback,
                                             z_closure_drop_t on_close,
                                             z_error_t *e);

bool z_session_delete(const z_session_t *session,
                      const z_keyexpr_t *key_expr,
                      const z_congestion_control_t *congestion_control,
                      const z_priority_t *priority,
                      const bool *express,
                      z_zbytes_t *attachment,
                      z_error_t *e);

void z_session_drop(z_session_t *this_);

bool z_session_get(const z_session_t *session,
                   const z_keyexpr_t *key_expr,
                   const char *parameters,
                   const int64_t *timeout_ms,
                   const z_query_target_t *target,
                   const z_consolidation_mode_t *consolidation,
                   const z_reply_key_expr_t *accept_replies,
                   const z_congestion_control_t *congestion_control,
                   const z_priority_t *priority,
                   const bool *express,
                   z_zbytes_t *payload,
                   const z_encoding_t *encoding,
                   z_zbytes_t *attachment,
                   z_closure_reply_t callback,
                   z_closure_drop_t on_close,
                   z_error_t *e);

z_zenoh_id_t *z_session_peers_zid(const z_session_t *session, uintptr_t *len);

bool z_session_put(const z_session_t *session,
                   const z_keyexpr_t *key_expr,
                   z_zbytes_t *payload,
                   const z_encoding_t *encoding,
                   const z_congestion_control_t *congestion_control,
                   const z_priority_t *priority,
                   const bool *express,
                   z_zbytes_t *attachment,
                   z_error_t *e);

z_zenoh_id_t *z_session_routers_zid(const z_session_t *session, uintptr_t *len);

bool z_session_undeclare_keyexpr(const z_session_t *session, z_keyexpr_t *key_expr, z_error_t *e);

z_zenoh_id_t z_session_zid(const z_session_t *session);

void z_subscriber_drop(z_subscriber_t *this_);

void z_timestamp_drop(z_timestamp_t *this_);

uint8_t *z_timestamp_id(const z_timestamp_t *t, uintptr_t *len);

int64_t z_timestamp_ntp64(const z_timestamp_t *t);

void z_try_init_zenoh_logs_from_env(void);

z_zbytes_t z_zbytes_clone(const z_zbytes_t *z);

void z_zbytes_drop(z_zbytes_t *this_);

z_zbytes_t z_zbytes_from_slice(const uint8_t *bytes, uintptr_t bytes_len);

uint8_t *z_zbytes_to_bytes(const z_zbytes_t *z, uintptr_t *len);

void z_zenoh_id_drop(z_zenoh_id_t *this_);

uint8_t *z_zenoh_id_to_bytes(const z_zenoh_id_t *z, uintptr_t *len);

char *z_zenoh_id_to_string(const z_zenoh_id_t *z);

#endif  /* ZENOH_FLAT_H */
