//! Hand-written [`prebindgen::Gravestone`] *logic* for the inline-by-value
//! (`value_opaque`) opaque counterpart types.
//!
//! Only the type-specific logic lives here: what an empty value is, and how to
//! detect it. The opaque struct (`crate::z_zbytes_t`) and its
//! [`prebindgen::Transmute`] impl (the unsafe rust<->opaque glue) are generated
//! into the bindings; the opaque-side `gravestone()`/`is_gravestone()` are
//! autoprovided via `Transmute`. So no `unsafe`/transmute is needed here.
//!
//! For `ZZBytes`, an *empty* `ZBytes` is the gravestone — cheaply constructed and
//! safe to drop — mirroring zenoh-c.

impl ::prebindgen::Gravestone for crate::z_zbytes_t {
    fn rust_gravestone() -> zenoh_flat::ZZBytes {
        zenoh_flat::ZZBytes::default()
    }
}

impl ::prebindgen::Gravestone for crate::z_sample_t {
    fn rust_gravestone() -> zenoh_flat::ZSample {
        zenoh_flat::ZSample::empty()
    }
}

impl ::prebindgen::Gravestone for crate::z_reply_t {
    fn rust_gravestone() -> zenoh_flat::ZReply {
        zenoh_flat::ZReply::empty()
    }
}

impl ::prebindgen::Gravestone for crate::z_query_t {
    fn rust_gravestone() -> zenoh_flat::ZQuery {
        zenoh_flat::ZQuery::empty()
    }
}

impl ::prebindgen::Gravestone for crate::z_hello_t {
    fn rust_gravestone() -> zenoh_flat::ZHello {
        zenoh_flat::ZHello::empty()
    }
}

// `ZEncoding`'s gravestone is the default encoding (`Encoding::default()` =
// `ZENOH_BYTES`, id 0 / no schema) — cheaply constructed and safely droppable.
impl ::prebindgen::Gravestone for crate::z_encoding_t {
    fn rust_gravestone() -> zenoh_flat::ZEncoding {
        zenoh_flat::ZEncoding::default()
    }
}

// NOTE: `crate::z_timestamp_t` and `crate::z_zenoh_id_t` are declared
// `opaque_data_struct` (plain `Copy` PODs, own no external data), so they need no
// `Gravestone` impl — only the autogenerated `Transmute`.
