//! Hand-written [`prebindgen::Gravestone`] *logic* for the inline-by-value
//! (`value_opaque`) opaque counterpart types.
//!
//! Only the type-specific logic lives here: what an empty value is, and how to
//! detect it. The opaque struct (`crate::z_zbytes_t`) and its
//! [`prebindgen::Transmute`] impl (the unsafe rust<->opaque glue) are generated
//! into the bindings; the opaque-side `gravestone()`/`is_gravestone()` are
//! autoprovided via `Transmute`. So no `unsafe`/transmute is needed here.
//!
//! For `ZZBytes`, an *empty* `ZBytes` is the gravestone — cheaply constructed and
//! safe to drop — mirroring zenoh-c.

impl ::prebindgen::Gravestone for crate::z_zbytes_t {
    fn rust_gravestone() -> zenoh_flat::ZBytes {
        zenoh_flat::ZBytes::default()
    }
}

impl ::prebindgen::Gravestone for crate::z_sample_t {
    fn rust_gravestone() -> zenoh_flat::Sample {
        zenoh_flat::Sample::empty()
    }
}

impl ::prebindgen::Gravestone for crate::z_reply_t {
    fn rust_gravestone() -> zenoh_flat::Reply {
        zenoh_flat::Reply::empty()
    }
}

// A failed reply's error: empty payload + default encoding — cheaply
// constructed and safely droppable.
impl ::prebindgen::Gravestone for crate::z_reply_error_t {
    fn rust_gravestone() -> zenoh_flat::ReplyError {
        zenoh_flat::ReplyError::default()
    }
}

impl ::prebindgen::Gravestone for crate::z_query_t {
    fn rust_gravestone() -> zenoh_flat::Query {
        zenoh_flat::Query::empty()
    }
}

impl ::prebindgen::Gravestone for crate::z_hello_t {
    fn rust_gravestone() -> zenoh_flat::Hello {
        zenoh_flat::Hello::empty()
    }
}

// `ZEncoding`'s gravestone is the default encoding (`Encoding::default()` =
// `ZENOH_BYTES`, id 0 / no schema) — cheaply constructed and safely droppable.
impl ::prebindgen::Gravestone for crate::z_encoding_t {
    fn rust_gravestone() -> zenoh_flat::Encoding {
        zenoh_flat::Encoding::default()
    }
}

// NOTE: `crate::z_timestamp_t` and `crate::z_zenoh_id_t` are declared
// `opaque_data_struct` (plain `Copy` PODs, own no external data), so they need no
// `Gravestone` impl — only the autogenerated `Transmute`.
